### ISSUE TITLE
Can not upload data on creation of Data entity - Code 500 internal server issue

### ISSUE THREAD

**Issue by cchara63** [european-dynamics-rnd/OneNet#6] opened 2022-09-28 12:44 UTC
Hello,

I am trying to upload a document with Onenet Local application. I selected the  "Provide data" below "Data Exchanges" and the "+New" button to create new Data entity. On the field "File" I have upload documents (.csv or .txt or .xlsx), but when I try to save this Entity an error message is presented "Code 500 internal server issue". 

Why does this happened? Why I can not upload documents in this Data Entity? 

![image](https://user-images.githubusercontent.com/106663426/192781665-8bd72e2d-edbb-4f39-a2c8-ab8a3a30ddf4.png)

Thank you for your time,
Charalambos Charalambous (University of Cyprus - KIOS)

**Comment by HeliasEurodyn** [comment] 2022-10-05 14:27
Hello, it is not an issue of Uploading the file. 
The issue is on the installation of the docker containers & Onenet Local Application. 

Please check 
1. if you installed properly the Onenet Local Application by Clicking the "Check Connection" button on the "Connector Settings".
2. if you properly deployed the docker containers 
3. If you properly configured the adresses of "Data App", "Ecc Url", "Broker Url" on the "Connector Settings".

<img width="1890" alt="Στιγμιότυπο 2022-10-05, 5 24 31 μμ" src="https://user-images.githubusercontent.com/47740658/194085431-76e2ffa4-fef4-4f52-bd70-e5ec2c3121ef.png">

Please let us know if it worked.

**Comment by vsakas** [comment] 2022-10-13 07:17
Charalambos, if this issue has been resolved, please close it.
 Otherwise please revert to us again.

Best regards,

Vassilis

**Comment by cchara63** [comment] 2022-10-13 14:24
thank you for your help!

**Comment by HeliasEurodyn** [comment] 2022-10-14 09:27
Hello @cchara63.


1. Regarding "Data App" & "Ecc Url", those ust Be Publicly Exposed In A Static Ip Via Https To Be Served As An Endpoint For Peer To Peer File Transfer.
By the Onenet Architecture, the required files to be transferd from/to your premisses to other consumers/providers are encrypted and shared peer to peer, through those Ips/Ports, that's why this is not an option to leave them on localhost.

2. Regarding "My Subscription" form, it was a temporary minor issue that was appeared yesterday after deploying a new release. It works now.

**Comment by cchara63** [comment] 2022-10-14 14:35
Dear @HeliasEurodyn,

1. I will confirm that "Data App" & "Ecc Url" are be Public Exposed in Static Ip ASAP!
2. "My Subscription" and "Provide Data/ Consume Data" are operating now. 

Thank you for your help!
Charalambos

**Comment by cchara63** [comment] 2022-10-17 14:48
Hi Helia,

I had a talk with IT department and they said to me, the way they expose port in public is through Reverse Proxies or using webservers like HA proxy. So they asking me if this docker supports this kind of communication. For example the can give us public URL   (eg: https://kiosexample.ucy.ac.cy/test ) which will point to ---> internalPcdockerhostip:8084, https://kiosexample.ucy.ac.cy/data --> aninternalPcdockerip:8889. 

Thank you,
Charalambos

**Comment by ferdinandobosco** [comment] 2022-10-24 09:55
Dear Charalambos,
since the communication is over internet I don’t see any issue on using a reverse proxy with naming instead of ip and port. Please proceed in this way and come back to us for any kind of issue.

Ferdinando

**Closed** 2022-10-27 06:52 UTC
